### ISSUE TITLE
Todo List

### ISSUE THREAD

**Issue by yuri-kiss** [surv-is-a-dev/gallery#27]
**Gallery Updates**
 - [ ] Add the sandboxed and unsandboxed tag.
 - [x] Add switch case description
 - [ ] Fix Try Catch thumbnail (https://github.com/surv-is-a-dev/gallery/issues/17)

**Rewrite, Fix and Update some extensions**

Update:
 - [ ] Document events
 - [ ] Spell check
 - [ ] Buffers

Fix:
 - [ ] More Buttons
 - [ ] Fake Crashes
 - [x] More Fields

Rewrite:
 - [ ] Script Management
 - [ ] Breaking eternity
 - [ ] MimeDB
 - [ ] Image Blocks

(Maybe) List [and finish]:
 - [ ] Post message

**Comment by yuri-kiss** [comment]
i dont want a todo list, i will do what i feel is needed right now
